sdk_compile_definitions(-DCONFIG_ECAT_FOE_CHANNEL=1)

sdk_inc(${CMAKE_CURRENT_LIST_DIR}/ecat)
sdk_inc(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src)

sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/bootmode.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/ethercat_charger.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/coeappl.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/ecatappl.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/ecatcoe.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/ecatfoe.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/ecatslv.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/mailbox.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/objdef.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/sdoserv.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/SSC/Src/foeappl.c)

sdk_inc(${CMAKE_CURRENT_LIST_DIR}/ecat/port)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/port/hpm_ecat_hw.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/port/hpm_ecat_phy.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/port/hpm_ecat_e2p_emulation.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/port/hpm_ecat_foe.c)

sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/ecat_foe_support.c)
sdk_src(${CMAKE_CURRENT_LIST_DIR}/ecat/ecat_slave.c)
