/*
 * Project flash map for HPM5E31 LuckyCAT, 1MB QSPI NOR.
 *
 * The HPM OTA middleware includes this file through ota_kconfig.h when it is
 * present in the application include path.
 */
#ifndef ETHERCAT_CHARGER_HPM_FLASHMAP_H
#define ETHERCAT_CHARGER_HPM_FLASHMAP_H

#define FLASH_SECTOR_SIZE        (0x1000)
#define FLASH_ADDR_BASE          (0x80000000)
#define FLASH_START_ADDR         (0x00000000)
#define FLASH_MAX_SIZE           (0x00100000)

#define FLASH_EXIP_INFO_ADDR     (FLASH_START_ADDR)
#define FLASH_EXIP_INFO_SIZE     (0x00000400)

#define FLASH_NORCFG_OPTION_ADDR (FLASH_EXIP_INFO_ADDR + FLASH_EXIP_INFO_SIZE)
#define FLASH_NORCFG_OPTION_SIZE (0x00000C00)

#define FLASH_BOOT_HEADER_ADDR   (FLASH_NORCFG_OPTION_ADDR + FLASH_NORCFG_OPTION_SIZE)
#define FLASH_BOOT_HEADER_SIZE   (0x00002000)

#define FLASH_BOOT_USER_ADDR     (FLASH_BOOT_HEADER_ADDR + FLASH_BOOT_HEADER_SIZE)
#define FLASH_BOOT_USER_SIZE     (0x00040000)

#define FLASH_USER_KEY_ADDR      (FLASH_BOOT_USER_ADDR + FLASH_BOOT_USER_SIZE)
#define FLASH_USER_KEY_SIZE      (0x00000000)

#define FLASH_USER_APP1_ADDR     (FLASH_BOOT_USER_ADDR + FLASH_BOOT_USER_SIZE)
#define FLASH_USER_APP1_SIZE     (0x00056000)

#define FLASH_USER_APP2_ADDR     (FLASH_USER_APP1_ADDR + FLASH_USER_APP1_SIZE)
#define FLASH_USER_APP2_SIZE     (0x00056000)

#define FLASH_DIFF_APP_ADDR      (FLASH_USER_APP2_ADDR + FLASH_USER_APP2_SIZE)
#define FLASH_DIFF_APP_SIZE      (0x00000000)

#define FLASH_EEPROM_ADDR        (0x000EF000)
#define FLASH_EEPROM_SIZE        (0x00010000)

#define FLASH_USER_COMMON_ADDR   (0x000FF000)
#define FLASH_USER_COMMON_SIZE   (0x00001000)

#if ((FLASH_USER_COMMON_ADDR + FLASH_USER_COMMON_SIZE) > FLASH_MAX_SIZE)
#error "flash map error"
#endif

#endif

